import { DocsSidebarNav } from '@/components/app/sidebar-nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const items = [
    {
      title: "Expenses",
      href: "/expenses"
    }
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <DocsSidebarNav items={items} />
        <main>{children}</main>
      </body>
    </html>
  )
}
