import { DocsSidebarNav } from "@/components/ui/sidebar-nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const items = [
    {
      title: "Finances",
      items: [
        {
          title: "Home",
          href: "/",
        },
        {
          title: "Expenses",
          href: "/expenses",
        },
        {
          title: "Incomes",
          href: "/incomes",
        },
        {
          title: "Transfers",
          href: "/transfers",
        },
        {
          title: "Reports",
          href: "/reports",
        },
      ],
    },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex-1">
          <main className="flex-1 md:grid md:grid-cols-[220px_1fr] md:gap-6 lg:grid-cols-[240px_1fr] lg:gap-10">
            <aside className="fixed top-0 z-30 hidden h-screen w-full shrink-0 overflow-y-auto border-r py-6 px-2 md:sticky md:block lg:py-10">
              <DocsSidebarNav items={items} />
            </aside>
            <div className="pt-10">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
